name: Node.js CD

on:
  push:
    branches:
      - main  # Se activa cuando hay un push a la rama main.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # tu versión de Node.js

      - name: Install dependencies
        run: npm install  # Instala las dependencias del proyecto

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nodewebappdeploylucero'  # El nombre de tu app en Azure
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
